const initialState = {
    user: {
      id: '',
      username: '',
      password: '',
      name: '',
      address: '',
      age: 0,
      profileImage: null,
      medicalhistory: [],
      chat: [],
      appointment: [],
      payment: [],
      instantcall: [],
      Calllog: [],
    },
    doctor: {
      id: '',
      firstName: '',
      lastName: '',
      email: '',
      bio: '',
      phoneNumber: '',
      urls: [{ value: 'https://github.com'}, { value: 'https://linkedin.com'}],
      username: '',
      password: '',
      age: 0,
      dob: '',
      category: '',
      experience: '',
      aadhaar: '',
      clinic_location : false,
      home_location : false,
      current_location : false,
      detected_location: { lat: 0 , lng: 0 },
      location_terms: false,
      license: '',
      medicaldegree: ["mbbs"],
      degreepdf: null,
      profileImage: null,
      feedback: [],
      chat: [],
      Calllog: [],
      appointment: [],
      payment: [],
      instantcall: [],
      isProfileComplete: false,
      isAccountComplete: false,
      isCategoryComplete: false,
      isLocationComplete: false,
      isEducationComplete: false,
      registration: '',
    },
    token: {
      id: '',
    },
    info: {
      name: '',
      location: [],
      loginAs: '',
    },
    backend: {
      rootapi: "http://localhost:5000",
    }
  };

  export default initialState;